//
//  DefaultDataManager.swift
//  ParkourFlowGenerator
//
//  Created by Steven Sullivan on 11/15/23.
//

import Foundation

class DefaultsDataManager {
    
    let categoryNames: [String] = [
        "Flow Moves",
        "Vaults",
        "Flips",
        "Parkour",
        "Dismount Tricks",
        "Wall Tricks",
        "Bar Tricks",
        "Tricking",
        "Breakdancing"
    ]
    
    let flowMoves: [(name: String, about: String, linkString: String)] = [
            ("cartwheel", "A cartwheel is a sideways rotary movement of the body. It is performed by bringing the hands to the floor one at a time while the body inverts.", "https://www.youtube.com/shorts/oW7SThKkfTs"),
            ("swing cartwheel", "", ""),
            ("roundoff", "A roundoff (also called Arab(ian) Spring move) is a move in gymnastics similar to a cartwheel, except the gymnast lands with two feet placed together on the ground instead of one foot at a time, facing the direction of arrival.", "https://www.youtube.com/watch?v=gxGsEG_-7y4"),
            ("backhandspring", "A back handspring is a gymnastics maneuver that involves flipping backward, with hands touching the ground midway through the maneuver.", "https://www.youtube.com/watch?v=4nFNwsc4v1c"),
            ("macaco", "The Macaco is a backhandspring from a squatting position. It flips slightly over the side. This is a great move to slowly get over backflip fear and to work your way up to a backhandspring.", "https://www.youtube.com/watch?v=pMEi89EnjnU"),
            ("one handed carthweel","A cartwheel but placing only one hand (the one that is the same as the direction). For instance, a one-handed cartwheel to the right would be done with the right hand.", "https://www.youtube.com/shorts/flplf7SmaMs"),
            ("helicoptero", "A helicoptero is an Aú with a circular movement of the legs, like a helicopter. Helicoptero benefits from rotating at the spine. For this reason, make sure that you are thoroughly warmed up. The movement gets its name from the movement of the legs, which mimic a helicopter.", "https://youtu.be/zvuyULbb2u0?t=17"),
     ("pasha Tdr", "A touchdown raiz where both hands are placed without jumping from the ground.", "https://youtu.be/zvuyULbb2u0?t=26"),
     ("capoeira cart", "A cartwheel done in a piked pose.", "https://youtu.be/zvuyULbb2u0?t=48"),
            ("gumbi", "The base for all Raiz-type of tricks. Can be thought of as an arched, opposite-side cartwheel.", "https://www.youtube.com/shorts/oW2_BVR6QDc"),
            ("front roll", "A forward roll with hands going directly in between hands.", "https://www.youtube.com/watch?v=JvNNZCfOuiY"),
            ("kip up", "Springing up from shoulders and hands, rotating forward and landing directly on feet.", "https://youtu.be/T9Cq4NcvTQ4?t=6"),
            ("butt spin", "A common flow move which can be thought of as a horizontal roll.", "https://youtu.be/5iOJS-uJz48?t=3528"),
            ("roll kip up", "A front roll combined with a kip up off the hands and shoulders straight to feet.", "https://youtu.be/vIj0NJBslhs?t=137"),
            ("side roll", "A roll directly sideways from shoulder to shoulder and back to feet.", ""),
            ("side roll kip up", "A side roll but with spring up to feet midway through.", ""),
            ("suicide kip up", "A standing jump backwards to hands, then shoulders, then kip up back to feet. Also known as a rubber band.", "https://www.youtube.com/watch?v=2GfY4AMwpxs"),
            ("hook swing crescent over obstacle", "A common flow move consisting of a backwards hook-type kick, then a forward kick, followed by a 180 spin.", ""),
     ("cartwheel pistol sideflip", "A cartwheel followed by a sideflip with body in a pistol pose.", "https://youtu.be/5iOJS-uJz48?t=7014"),
     ("gumbi spin vault", "A common flow move where hands or placed on an object and you spin vertifcally over using your hands to 180 before landing.", "https://youtu.be/5iOJS-uJz48?t=7018"),
            ("coffee grinder", "A common flow move derived from breakdancing. Crouching down on one leg, and doing a front sweep around before threading past your starting leg with a jump.", "https://www.youtube.com/watch?v=5B3WL_tJRzM"),
     ("scoot onto object", "A scoot onto an object, often in preparation for a bigger trick.", "https://youtu.be/5iOJS-uJz48?t=7020"),
            ("machine", "Similar to a scoot, but starting with opposite hand, normal hand, normal foot, opposite foot.", "https://www.youtube.com/shorts/QncNPUWReDQ"),
            ("machine to coffee grinder", "A machine landing facing 180 degrees from starting, straight into a coffee grinder.", "https://www.youtube.com/shorts/q6I-dNT7MSc"),
            ("freestyle flow move", "", ""),
            ("reverse step vault", "A reverse vault (180), with a backwards step out.", ""),
            ("palm spin", "Pre-requisite to a wall spin wherein the athlete rotates semi-vertically around both hands on the corner or ledge of an object.", "https://www.youtube.com/watch?v=h0_oyA7FC_o"),
    ("hyper palm spin", "A combo of a machine type entrance on a vault, but with full rotation back around to a lazy out of the front of the vault.", "https://www.youtube.com/watch?v=vsjK7isRWQw&ab_channel=BobReese"),
            ("machine palm spin", "A palmspin but with the opposite hand placed first before normal hand like in a machine.", "https://www.youtube.com/shorts/93fAxYe0qQ0"),
            ("machine onto vault", "A machine onto an object.", "https://www.youtube.com/shorts/LK0E-un5E7A"),
            ("lazy vault to s/t", "A lazy vault, but rather than landing with second foot, it swings straight through giving momentum for the next trick.", "https://www.youtube.com/shorts/iVxlpij20_Y"),
    ("kong up", "A two handed kong up onto an object.", "https://www.youtube.com/shorts/N9NLzR4uMlY")
        ]
        
    let vaults: [(name: String, about: String, linkString: String)] = [
            ("safety vault", "A vault where the athlete places their normal hand and opposite foot on an object in order to thread their leg through to step out onto the other side.", "https://www.youtube.com/watch?v=OZFnbIOmmIY"),
            ("two-handed safety vault", "A safety vault but with two hands placed on the object instead of one.", "https://youtu.be/uQemfIOarkA?si=xUpvehfkxW7aNjjW"),
            ("speed vault", "A safety vault with no foot placed on the object, but instead kicked back for momentum.", "https://youtu.be/XoBe07XoLTE?si=zFYD_GC8f92O-iCZ"),
            ("two-handed speed vault", "A simple speed vault with two hands.", "https://youtu.be/y9nLby7XKlk?si=7bhfqH2TxBSZg1CH"),
            ("gate vault", "Often used on gates. The athlete leans over and uses bottom hand as an anchor to swing their legs over the object.", "https://youtu.be/W_c0-4pC57E?si=loxvgw99eIlqthsF"),
            ("lazy vault", "A flowful vault where the inner leg is swung sideways over an object while the athlete switches hands, and kicks second leg over for a smooth step out landing.", "https://youtu.be/3bLX2VJZMgk?si=iyFF7WH_dNXGu5Vs"),
            ("lazy vault 180", "A lazy vault with a 180 twist at the end.", "https://youtu.be/lyHmoN1p-sE?si=QHXR_piVCAtF5wP1"),
            ("reverse vault", "A 360 vault led with only the opposite hand of spinning direction (right hand if spinning left).", "https://youtu.be/sXyyi4q1Jp4?si=zZey76R_yL-7SX1o"),
            ("360 vault", "A vault where the athlete places one or both hands and spins 360 degrees over the obstacle.", "https://youtu.be/6r6B00DXlUE?si=NmBhgAsonQZxQXlL"),
            ("540 vault", "A 360 vault with an extra 180 spin to land facing the obstacle they vaulted.", "https://youtu.be/XV7hDqFZ5MI?si=HKIRzNopQEdHO_OV"),
            ("dash vault", "A vault where the athlete clears the object with their feet out in front of their body, placing their hands below their lower back and pushing back to their feet on the other side.", "https://youtu.be/9E-QcfGC0rQ?si=UdiwWMBbNujYR3UO"),
            ("one-handed dash vault", "A dash vault with a single hand.", "https://youtu.be/NM1roAOpTZM?si=DeT0h8hnCbtUJ1Rk"),
            ("kong vault", "A vault where an athlete pushes off both hands to clear the object with their feet/legs staying straight down the middle over the object. Also known as cat pass or monkey vault.",  "https://youtu.be/lYhSqk6mLjE?si=cn6cAkh8I-RE4jL4"),
            ("one-handed kong vault", "A kong where the athlete uses one hand instead of two.", "https://youtube.com/shorts/GPR9CEodM5s?si=awkNFA8kkLVopNtn"),
            ("kash vault", "A combination of the kong vault, but the athlete pushes their legs through to end the vault with a dash vault out.", "https://youtu.be/_Nx5E8_24ro?si=mmvocnBlcMpnKhHA"),
            ("kong lazy", "A very popular flow move used to dismount objects smoothly. It is a kong entrance with a sweeping lazy out.", "https://youtu.be/FUvDOCCYXRg?t=145"),
            ("straddle vault", "A two-handed vault where both legs go on either side of the object. Useful for poles, columns, or other objects which aren’t very wide.", "https://youtube.com/shorts/ty1kbeEDuwc?si=l2YZhS9mj7b3GnFT"),
            ("inverse kong", "Also known as a reverse kong. A vault where the user throws their legs over the object and does a 180 to end in a position similar to the beginning of a kong, but in reverse.", "https://youtu.be/AzALBgK1qg8?si=TQNaw5HLTRWlFTc0"),
            ("double kong", "A kong where the user throws their legs up higher to initiate a second kong on the way down at the end of an object.", "https://youtu.be/dFOPLqDLt3U?si=Zx1gyD1OcC7iPgZu"),
            ("side roll vault", "A sideways shoulder roll over an object.", ""),
            ("roll vault", "A frontward roll over an object.", "https://youtu.be/oAcX8mz4Ji0?si=ZVwfZRijqb3Iy3Bx"),
            ("roll kip up vault", "A frontward roll where the user pushes up off their shoulders and hands to pop onto their feet.", "https://youtube.com/shorts/vX8pUWtTz8Q?si=GyCAB7MTg-ZPfCMY"),
            ("roll kip up 180 over obstacle", "A roll kip up with a 180 twist on the way down.", ""),
            ("front handspring vault", "A fronthandspring over an object.", "https://youtu.be/AJvyjSaJtQ0?si=bIoWgSXRP2QqXhCJ"),
            ("cartwheel vault", "A cartwheel over an object.", "https://youtube.com/shorts/HnaAI5QUzSY?si=TVrwCfJytXiFpGsi"),
     ("front handspring to sit", "A fronthand spring where the hips guide the athlete to a sitting position on an object.", ""),
            ("dash roll", "A pre-requisite to a dash bomb, where the athlete does a dash vault but rather than landing on feet, they kick their legs out and down, push from their hands, and skip their feet to land on their hands for a dive roll.", "https://youtu.be/x02DOUl82Xc?si=6xqQBtmu7l7OFQrA"),
            ("lazy roll", "A dive roll from a lazy vault where the athlete skips their feet on the landing.", ""),
            ("kong front flip", "A kong vault where the athlete pushes off their hands into a frontflip landing on the other side.", "https://youtu.be/yIglgVFob2o?si=LNIEhk1ExFWXP4A_"),
            ("side flip one-handed touch vault", "A sideflip over an object, placing the first hand on the object on takeoff.", ""),
            ("safety webster", "A safety vault where the athlete pauses and threads their leg back through and swings up into a webster with their hand still placed.", ""),
            ("kong front dash out", "A kong vault where the athlete pushes off their hands into a frontflip into a dash vault off the other side.", "https://youtu.be/gmal1tCsMPs?si=fBZlVdFBFRpmRzzZ"),
            ("kong step out", "A kong where the athlete uses a foot to guide them on the way down from the top of the object.", ""),
            ("kong dive roll", "A kong where the athlete pushes from their hands into a dive roll on the other side.", "https://youtube.com/shorts/mwmNucP21Pw?si=81bjxCbuKKB0HBtd"),
            ("cast monkey vault", "A cast on the front of an object where they throw their hips up, and then pull down into a kong to clear the object.", ""),
            ("worm kong", "A jump worm onto an object before raising onto hands to do a down kong from the object.", ""),
            ("sideways worm to switch leg", "A worm initiated from a sideways position over to the other side of the object landing on one leg for a swingthrough.", ""),
            ("reverse double leg", "A reverse vault intro into a double leg sideflip over.", "https://youtu.be/TfLT3RYoZ_w?si=Qpv7RXBELDRpilr3"),
            ("machine over vault", "A machine vault but rotating over to the other side of the object.", ""),
            ("freestyle vault", "Any vault you choose.", "")
        ]
        
        let tricking: [(name: String, about: String, linkString: String)] = [
            ("hook kick", "A backwards hooking kick.", "https://www.youtube.com/watch?v=k75LwxyYSps&ab_channel=MasteringTricking"),
            ("skip hook", "A hook kick initiated from a 180 intro.",  "https://www.youtube.com/watch?v=tMFpFMBU5kY"),
            ("crescent kick", "A crescent kick is a frontward kick starting by lifting the knee and jumping off the back leg initiating the kick with a circular motion.", "https://www.youtube.com/watch?v=3ThcHXPilVQ&ab_channel=UpraizTricking"),
    ("round kick", "A semicircle spin frontward extension kick.", "https://www.youtube.com/watch?v=cnxK1DdyPio&ab_channel=ZakFerguson"),
            ("pop 360", "A kick that starts facing forward, jumping from both feet, and then rotates 180° in the air, then lands and finishes with an outside crescent kick towards the target and lands in turbo (both feet).", "https://www.youtube.com/shorts/oG13xxzFGB0"),
            ("pop 540", "Pop (two feet takeoff) tornado kick hyper.", "https://www.youtube.com/watch?v=POYwNJcCQpw"),
            ("backside 720", "A skip hook off of two feet.", "https://youtu.be/yArws74DOXk?t=3"),
    ("backside 9", "A kick that starts in backside stance, leaves the ground off of both feet, rotates 540° in the air, then lands and finishes with a round kick towards the target.",  "https://www.youtube.com/watch?v=Gi7yVq-OQLc"),
            ("tornado kick", "A 360 spinning kick initiated with a knee up followed by a round kick during the spin.", "https://www.youtube.com/watch?v=-regnle5xqU"),
            ("back sweep", "A backwards sweeping kick while doing a 360 low-to-ground spin.", "https://www.youtube.com/watch?v=29vhsmw_oUk"),
     ("front sweep", "A frontward sweeping kick while doing a 360 low-to-ground spin.", "https://www.youtube.com/watch?v=gil8H175vSI"),
            ("tdr", "A low and fast Raiz where you touchdown with your hand, similar to a scoot, before your legs come down.", "https://www.youtube.com/shorts/cLdndAgV7PE"),
            ("raiz", "A no-handed Gumbi or a laid-back / arched Tornado where the body rotates over a horizontal axis.", "https://www.youtube.com/shorts/G0nOOh4meJo"),
            ("540 kick", "A tornado kick where the athlete skips their jumping foot on landing and instead lands on their kicking foot.", "https://www.youtube.com/shorts/kfUPlW3itZg"),
            ("sideswipe", "A laid back 540 kick over a horizontal axis.", "https://www.youtube.com/shorts/V1OffBoG_dM"),
            ("butterfly kick", "A horizontal double backwards kick while doing a 180 flatspin.", "https://www.youtube.com/watch?v=FD0Ht7YTlgU&ab_channel=Seung-niTraverseCityMartialArts%26KickboxingAcademy"),
            ("butterfly twist", "A butterfly kick with a 360 spin mid air rotation.", "https://www.youtube.com/shorts/kITQsIWtokE"),
            ("double b-twist", "A butterfly kick with a 720 spin mid air rotation.", "https://youtu.be/ZVnl7cFFgys?t=25"),
            ("flash kick", "A backflip with a flashed kick out on the second half before landing.", "https://www.youtube.com/watch?v=LFWeze_nztM&ab_channel=Johzuke"),
            ("j-step", "A common soccer-type kick where the athlete walks in a 2-3 step j motion before kicking upwards for momentum.", "https://www.youtube.com/watch?v=v9f7vjvIZ00&ab_channel=Johzuke"),
            ("cheat gainer", "Often done from a j-step, an upwards kick flipping the user over a diagonal axis back onto their kicking foot.", "https://www.youtube.com/watch?v=aNy4JpNBa58&ab_channel=RonnieStreetStunts"),
            ("gainer switch", "An upwards kick into a backflip / cheat gainer where the athlete lands on the jumping leg in preparation for another swingthrough trick.", "https://www.youtube.com/watch?v=lI_iCIai3aQ&ab_channel=KojosTrickLab"),
            ("cork", "A cheat gainer with a 360 spin or a kick into a 540 backwards flatspin.", "https://www.youtube.com/shorts/uvxGv5TadZU"),
    ("double cork", "A cork 2 spins before landing .", "https://www.youtube.com/watch?v=05-zP7tCVUs&ab_channel=PlanZero"),
    ("triple cork", "A cork with 3 spins before landing.", "https://www.youtube.com/watch?v=JO-2_zDJLrw&ab_channel=BAHT"),
            ("double leg", "A sideflip with both legs locked out straight in a pike with no hands holding them in.", "https://www.youtube.com/watch?v=HY1TIay4psA&ab_channel=HadynWiseman"),
            ("cork hyper", "A cork landing on the kicking foot.", "https://www.youtube.com/shorts/eaNR6ArlobE"),
            ("box cutter", "A cork hyper hook.", "https://www.youtube.com/watch?v=9x7PnzC3TNY&ab_channel=Johzuke"),
            ("jackknife", "A Cheat 720 with a round kick executed before the hook kick or a 540 that finishes with a hook kick. ", "https://www.youtube.com/watch?v=efwVetwCP-U&ab_channel=KojosTrickLab"),
            ("swipeknife", "A horizontal or inverted Cheat 720, pulling the Roundkick leg through straight instead of bent.", "https://www.youtube.com/watch?v=tt_w57yZUCM&ab_channel=Emptyjumpjo"),
            ("scoot", "A one-handed low step 180 spin used to generated momentum for a bigger tricking move.", "https://www.youtube.com/watch?v=ZlseIYawXiM&ab_channel=RonnieStreetStunts"),
            ("webster", "A backwards kick lifting the athlete off the ground into a frontward flip.", "https://www.youtube.com/watch?v=vIj0NJBslhs&ab_channel=RyanDoyle"),
            ("loser webster", "A webster traveling the backwards direction.", "https://www.youtube.com/watch?v=D0-KkOi8EcI&ab_channel=GingerNinjaTrickster"),
            ("webster 180", "A webster with a 180 spin.", "https://www.youtube.com/watch?v=4p3sLHDinNk"),
            ("webster 360", "A webster with a 360 spin landing toward the same forward direction.", "https://www.youtube.com/watch?v=E5rHizzc63k"),
            ("aerial", "A cartwheel with no hands.", "https://www.youtube.com/watch?v=rWwSk6z6xwc"),
            ("a-twist", "An aerial twisting 180 over the jumping foot.", "https://www.youtube.com/watch?v=m19rJecIGik"),
            ("double a-twist", "An aerial twisting 540 over the jumping foot.", "https://www.youtube.com/shorts/D8c3ulyLXZc"),
            ("triple a-twist", "An aerial twisting 900 over the jumping foot.", "https://www.youtube.com/watch?v=ovmAS4jeFVk"),
            ("crowd awakener", "A Tornado with a split kick / straddle.", "https://www.youtube.com/watch?v=da9W4y2dIBg"),
            ("shuriken", "A spread leg kicking pose initiated mid trick.", "https://www.youtube.com/watch?v=WXsFkRtP5C0&ab_channel=Johzuke"),
            ("shuriken twist", "A b-twist with a straight kick over your twisting leg in the second half.", "https://www.youtube.com/watch?v=37JicKEixLs&ab_channel=TheTrickingAcademy"),
            ("b-twist round", "A b-twist with a round kick outro.", "https://www.youtube.com/watch?v=aGCEouurH3A"),
            ("sailor moon", "A Raiz where the right hand (assuming left twisting) is planted right before take-off.", "https://www.youtube.com/watch?v=8A_IKld35sk"),
            ("valdez", "A one-handed back handspring that’s slightly off-axis.", "https://www.youtube.com/watch?v=A7lzmG8e84c"),
            ("masterswipe", "A swingthrough cartwheel kicking the lead leg over back leg in the intro.", "https://www.youtube.com/watch?v=6BFUyGy0aAw"),
            ("grand masterswipe", "A masterswipe without hands: swingthrough aerial sideflip kicking the leading leg over and past the back leg.", "https://www.youtube.com/watch?v=PC3Tmj7HAIQ&ab_channel=KojosTrickLab"),
            ("donut boy", "A piked flatspin with a straight leg tuck making a sharp angle with your torso, hands hold behind the knee.", "https://www.youtube.com/watch?v=uAy2EWpvjhU&ab_channel=Moreira1986"),
            ("b-twist double leg", "A b-twist in a double leg (no-handed pike) pose.", "https://www.youtube.com/watch?v=ZI6JZ1x0ue8&ab_channel=federico00"),
            ("cork round", "A cork with a roundhouse kick out.",  "https://www.youtube.com/shorts/vT4vowo3UD0"),
            ("gainer rocketboii",  "A gainer with a slightly piked pose and one hand grabbing feet.", "https://www.youtube.com/watch?v=4WevGtTBw7g&ab_channel=KapuTricking"),
            ("360 suicide kip up", "A rubber band / suicide kip up with a 360 spin on the way down.", "https://www.youtube.com/watch?v=GCzFNm_NZbY&ab_channel=BobReese"),
            ("back full hyper hook", "A backflip 360 with a hyper hook out.", "https://www.youtube.com/watch?v=G0U3uS2HHTY&ab_channel=MasteringTricking"),
            ("flash full", "A flash kick intro into a backflip 360.", "https://www.youtube.com/watch?v=kcsdbIrC5xA&ab_channel=BrandonMccuien"),
            ("kroc (cork off opposite foot)", "A cork taking off the opposite foot.", "https://www.youtube.com/watch?v=QO9yFRIpjoE&ab_channel=Pkspark"),
            ("webster x-out", "A webster with an x-out pose on the second half.", "https://www.youtube.com/watch?v=26WBEfkVcSU&ab_channel=IGContestcom"),
            ("snatchcannon (cork-in back-out)", "A corkscrew into a backflip in midair.", "https://www.youtube.com/watch?v=lphBYujvQ0s&ab_channel=BAHT"),
            ("to splits", "Land a trick in the splits position.", "https://www.youtube.com/watch?v=F_jiXfVTHpk&ab_channel=JoeyTheJAM"),
            ("to ninja pose landing", "Land a trick in a ninja pose with one arm out and the other placed on the ground.", "https://youtu.be/t5TE94MD2Oo?t=536"),
            ("freestyle tricking move", "Any tricking move you want.", "")
        ]
        
        let flips: [(name: String, about: String, linkString: String)] = [
            ("dive roll", "A frontward dive onto your hands finishing in a forward roll.", "https://youtu.be/tUJwUUAiT4o?t=16"),
            ("front flip", "A frontward flip over your head back ontro your feet, usually done off of a two-footed jump or punch.", "https://www.youtube.com/watch?v=oTGP1xptqak"),
            ("russian front", "A frontflip with arms thrown behind back on takeoff.", "https://www.youtube.com/watch?v=Tnh-B-Et51w"),
            ("front pike", "A frontflip in the piked positions (an undertuck with straight legs.)", "https://www.youtube.com/shorts/3eaNmie_m8o"),
            ("superman frontflip", "A frontflip with a superman stall.", "https://www.youtube.com/shorts/sM__MTV7Jyg"),
            ("frontflip 180", "A frontflip with a 180 twist.", "https://www.youtube.com/watch?v=wDIF-5qa5uo"),
            ("front 360", "A frontflip with a 360 twist.",  "https://www.youtube.com/shorts/DYuYdLXI7Hw"),
    ("360 Dive Frontflip","A 360 spin dive into a frontflip on the second half.",  "https://www.youtube.com/watch?v=kxU9_ruqMio"),
            ("frontflip 540", "A frontflip with a 540 twist.", "https://www.youtube.com/watch?v=SC0bYFgFDdk"),
            ("frontflip 720", "A frontflip with a 720 twist.", "https://www.youtube.com/shorts/iGEXbfEIkr0"),
            ("frontflip 900", "A frontflip with a 900 twist.", "https://www.youtube.com/shorts/zA-piuUIH1o"),
            ("back tuck", "A fundamental freerunning move where the athlete jumps off both feet, flipping backwards over their head in a tucked ball position.", "https://www.youtube.com/shorts/lgB3TBswpog"),
            ("back layout", "A backflip where the body is laid out straight while in the air.", "https://www.youtube.com/watch?v=WY79Z_cVydE"),
            ("back pike", "A backflip in the straight leg undertucked position.", "https://youtu.be/Fc1uhQrYq_E?t=112"),
            ("back undertuck", "A tuck backflip where the athlete grabs under their knees instead of over.", "https://youtu.be/Fc1uhQrYq_E?t=136"),
            ("stall backflip", "A backflip with a straight stall at the beginning and their arms out to the side.", "https://www.youtube.com/shorts/hpszG7DfXYI"),
            ("rodeo out backflip", "A tuck backflip that pulls the ankles out into a scorpion like arch before landing.", "https://www.youtube.com/watch?v=jGjkuWxlllE"),
            ("rocket boy backflip", "A backflip where the athlete grabs a straight leg pike with one hand on their feet.", "https://www.youtube.com/shorts/8e93kKFxSiM"),
            ("criss cross to backflip", "A backflip that starts from criss cross applesauce.", "https://www.youtube.com/shorts/UlM8-ATS9II"),
            ("backflip nike", "A backflip in the nike pose (one leg half-tucked, the other out straight almost in a pike.)", "https://www.youtube.com/shorts/E5WQmnCq3W4"),
            ("hands in pocket backflip", "A backflip with hands in pockets (harder than it sounds).", "https://www.youtube.com/shorts/1G__h0k8skA"),
            ("backflip x-out", "A backflip where the athlete flashes their legs out in both direction to form an x shape before landing.", "https://www.youtube.com/watch?v=recmYTXdB_I&t=16s"),
            ("low backflip", "A tucked backflip done as low as possible.", "https://www.youtube.com/shorts/_g7AxsJQ5Vk"),
            ("one-legged backflip", "A backflip off one leg.", "https://www.youtube.com/shorts/OoyZl0yl8Xo"),
            ("backflip to lay down (fake fail)", "A backflip where the athlete fakes landing badly on their stomach but does so in a safe, break fall.", "https://youtu.be/t5TE94MD2Oo?t=640"),
            ("misleg frontflip", "A split-leg intro frontflip where instead of taking off of the leading foot, the athlete pulls it up and backwards to miss that leg into the frontflip.", "https://www.youtube.com/shorts/-5m4Sc4_rh8"),
            ("misleg sideflip", "A split-leg intro sideflip where instead of taking off of the leading foot, the athlete pulls it up and past the back leg to miss the front leg into the sideflip.", "https://www.youtube.com/shorts/99FQEgwf7ac"),
    ("misleg sidefull", "A missleg sideflip into a full spin (more like 450 degree).", "https://www.youtube.com/shorts/uYbLlSkst9s"),
            ("gainer tuck", "A forwards backflip tucked in a ball.", "https://youtu.be/5NZYTN31IAY?t=9"),
            ("gainer layout", "A forwards backflip laid out straight.",  "https://www.youtube.com/watch?v=74ziK3zXuZE"),
            ("gainerabian",  "A forwards arabian tucked in a ball.", "https://www.youtube.com/watch?v=-bw_5rNFI3A"),
            ("running gainer", "A running forwards-traveling backflip.", "https://www.youtube.com/shorts/THT7zxvGR-I"),
            ("side traveling backflip", "A backflip traveling in the sideways direction.", "https://www.youtube.com/shorts/tQS_KYUxgDw"),
    ("pistol backflip", "Similar to a nike backflip but with legs switched and the non-extended leg more tucked in.", "https://youtu.be/e0BqaVqJ7vs?t=134"),
            ("backflip 180", "A backflip with a 180 spin initiated in the second half.", "https://www.youtube.com/shorts/d_p6RPtu_Tw"),
            ("arabian", "A backwards facing jump into a 180 spin into a frontflip.", "https://www.youtube.com/watch?v=VXDOtpPKxUc"),
            ("back full", "A backflip with a 360 spin.", "https://youtu.be/25vo0bKsQjk?t=48"),
            ("backflip 540", "A backflip with a 540 spin", "https://www.youtube.com/shorts/QkaL-8Dvj5k"),
            ("360 dive roll", "A dive roll with a 360 spin on takeoff.", "https://www.youtube.com/watch?v=anQu7upu0i8"),
            ("540 dive roll", "A half backflip with a 540 spin into a dive roll.", "https://www.youtube.com/shorts/iFm7bvkliq8"),
            ("back double full", "A backflip with two full spins.", "https://www.youtube.com/watch?v=CXpA9WI5T-o"),
            ("sideflip", "A sideways flip often over the shoulders.", "https://www.youtube.com/watch?v=8I7fHSGHrM8"),
            ("undertuck sideflip", "A sideflip with legs tucked underneath rather than over.", "https://www.youtube.com/shorts/kFMB2C-YGFY"),
            ("stall sideflip", "A sideflip with a stall pose at the beginning.", "https://youtu.be/K2Dsbnoue6A?t=25"),
            ("sideflip hyper", "A sideflip landing on the leading leg and spinning an extra 90 on landing.", "https://youtu.be/QObS8PUPZJU?t=7"),
            ("side full", "A sideflip with a late full 360 spin.", "https://www.youtube.com/watch?v=EpuX2vYK1Jg"),
            ("inverted sideflip", "A sideflip traveling backwards.", "https://www.youtube.com/watch?v=ph7xCQppr0k"),
            ("tunnel flip", "A running one footed swing sideflip traveling forwards.", "https://youtu.be/CB-lrc0wE6U?t=24"),
            ("double backflip", "Two backflips in the air before landing.", "https://www.youtube.com/watch?v=cVKg4vV3saU"),
            ("double sideflip", "Two sideflips in the air before landing.", "https://www.youtube.com/watch?v=BgvN6oT_MUY"),
            ("double frontflip", "Two frontflips in the air before landing.", "https://www.youtube.com/watch?v=jM4Gxp2FOKM"),
            ("gainer full", "A gainer backflip with a 360 spin.", "https://www.youtube.com/watch?v=2FbCSkjaXvs"),
            ("gainer double full", "A gainer backflip with a 720 spin.", "https://youtu.be/qiQf621Y56s?t=6"),
            ("double gainer", "A forward traveling two backflips in air before landing.", "https://www.youtube.com/shorts/ANvZRyTPlDY"),
            ("back full down", "A back tuck with a 360 spin on the second half.", "https://www.youtube.com/watch?v=_Dl5q0adwks"),
    ("arms behind back sideflip", "A sidelfip with hands behind back holding onto each other.", "https://youtu.be/5iOJS-uJz48?t=6861"),
            ("freestyle flip", "Any flip you want.", "")
        ]
        
        let dismountTricks: [(name: String, about: String, linkString: String)] = [
            ("dash bomb", "A dash vault into a frontflip skipping the feet.", "https://www.youtube.com/watch?v=7Xxboaid804&ab_channel=RonnieStreetStunts"),
            ("kong gainer",  "A kong vault into a gainer backflip skipping the feet.", "https://www.youtube.com/watch?v=xcJv60Llr-Q&ab_channel=YGTFreerunning"),
            ("castaway", "A backflip off of hands from a cast kick down.", "https://www.youtube.com/watch?v=E3gdT35kIpc&ab_channel=piptrix"),
            ("low cast", "A castaway purposely done low to the ground with little height for speed.", "https://www.youtube.com/watch?v=wxSmrkjmUhs&ab_channel=WATOYA"),
            ("dive cast", "A diving jump to hands to a castaway.", ""),
            ("cat cast", "A cat position on a wall or rail springing up into a castaway down.", "https://www.youtube.com/watch?v=F4aBAGTMt_I&ab_channel=MickyAflalo"),
            ("hanging cast", "A backflip from hands done after a worm type cast from a hanging position.", "https://www.youtube.com/watch?v=QBjpqtmupuI&ab_channel=NickPro"),
            ("macaco cast", "A one or two handed off-axis backhandspring into a backflip skipping feet.", "https://www.youtube.com/watch?v=41ECXm9Hyr0&ab_channel=Tresk"),
            ("pimp flip", "A sideways backflip off one or both hands from the top of a ledge.", "https://www.youtube.com/watch?v=6KLJIQnwLAI&ab_channel=BobReese"),
    ("gaet flip", "A sideways backflip from a two handed swing often done from ground-level height..", "https://www.youtube.com/watch?v=S4T64GCi9ws&ab_channel=Tresk"),
            ("roll bomb", "A front roll into a frontflip skipping feet off of an object.", "https://www.youtube.com/watch?v=SKfH6PzGWGs&ab_channel=MATraceur"),
            ("cartahara", "A cartwheel into a sideflip skipping feet.", "https://www.youtube.com/shorts/xCHpmH0-Bvs"),
            ("tsukahara", "A roundoff into a backflip skipping feet.", "https://www.youtube.com/watch?v=aJ600eOuWtI&ab_channel=LearnGymnasticsOnline"),
            ("angel drop", "A cat hang into a wall-step into a backflip.", "https://www.youtube.com/watch?v=gRhwjTf1Inc&ab_channel=EthanGuzman"),
            ("devil drop", "A cat hang into a frontflip.", "https://www.youtube.com/watch?v=sPtaINcJ56Q&ab_channel=RonnieStreetStunts"),
            ("demon drop",  "A cat hang into a sideflip.", "https://youtu.be/NanTsgzGOmY?t=13"),
            ("cat dismount",  "A cat hang into a drop down to feet.", "https://www.youtube.com/watch?v=_xLMtfgCaXE&ab_channel=ThenBosx"),
            ("gate vault dismount", "A gatevault down from a ledge onto the ground.", "https://www.youtube.com/shorts/ujgEHefcP_8"),
            ("drop and roll", "A jump off of an object to a safety roll.", "https://www.youtube.com/watch?v=ZTlEwMtDH9s&ab_channel=RonnieStreetStunts"),
            ("handstand dismount", "A handstand on a ledge to a down kong.", "https://www.youtube.com/shorts/ysshAT2-hP4"),
            ("down kong", "A kong down a ledge.", "https://www.youtube.com/watch?v=R8Z21VqQzV0&ab_channel=FirestormFreerunning"),
            ("cast loser frontflip", "A cast into a loser frontflip off hands.", "https://www.youtube.com/watch?v=gCFloU0_bg0&ab_channel=UrbanMotivation"),
            ("macaco full", "A macaco with a full spin before landing off of an object.", "https://youtu.be/YaSv1ZKLvo4?t=44"),
            ("freestyle dismount", "Any dismount from a ledge.", "")
        ]
        
        let wallTricks: [(name: String, about: String, linkString: String)] = [
            ("one step palmflip", "A palmflip after a one step vertical wall run.", "https://youtu.be/5iOJS-uJz48?t=7642"),
            ("wallflip", "A one step backflip off a wall.", "https://www.youtube.com/shorts/_Jx6dhK-tVI"),
            ("wall arabian", "A one step arabian off a wall.", "https://www.youtube.com/watch?v=7T0lNfbfAiQ"),
            ("wallflip 180", "A 1 step wall backflip with a 180 spin.",  "https://www.youtube.com/watch?v=HguwiHn0zz4"),
            ("wall full", "A one step wall backflip with a 360 spin.", "https://www.youtube.com/watch?v=fuACTt-QP7c"),
            ("wall inverted front", "A one step loser frontflip off a wall.", "https://www.youtube.com/watch?v=Z-IE1hbiIlE"),
            ("wall inverted front half", "A one step loser frontflip 180 off a wall.", "https://www.youtube.com/shorts/vPRCZb09F18"),
     ("trap door", "A two footed punch backflip off a wall; often with a drop.", "https://www.youtube.com/shorts/XkAt2hjqxMM"),
     ("wall flare", "A breakdancing flare done on a vertical wall.", "https://www.youtube.com/watch?v=uvKHWwH0TA0"),
            ("wall inverted sideflip", "A one step loser sideflip off a wall.", "https://www.youtube.com/watch?v=ZwxCY953I6I"),
            ("trinity flip", "A two step outward sideflip off a wall from a scene in the Matrix.", "https://www.youtube.com/watch?v=vInITvGS0qE"),
            ("wall gainer", "A one step 90 turn into a gainer off a wall.", "https://www.youtube.com/results?search_query=wall+gainer+ryan+doyle"),
            ("wallspin", "A palmspin on a vertical wall.", "https://www.youtube.com/watch?v=RdppbBTTrak"),
            ("wall raiz", "A raiz on a vertical wall.", "https://www.youtube.com/watch?v=rSJ_Sx8YytY"),
            ("ginger flip", "A one handed push into a gainer from a column or tree.", "https://www.youtube.com/watch?v=7Gsx073Fazw"),
            ("reverse wallspin", "A one handed reverse palmspin off a wall.", "https://www.youtube.com/watch?v=eq6jAVtnsZ0"),
            ("rayden", "A loser front handsrping off a wall.", "https://www.youtube.com/watch?v=ov--JbIGqYA"),
            ("palmflip", "A back tuck off of two hands from a wall.", "https://www.youtube.com/shorts/KvRAB9UV_YY"),
    ("low palmflip", "A back tuck from two palms intentionally done on a low wall or bar.", "https://www.youtube.com/watch?v=bZKZv8FX95Q&ab_channel=teamfarang"),
            ("down monkey", "A back handspring gainer off a wall.", "https://youtu.be/a3arD3-yvkc?t=19"),
    ("reverse down monkey", "A front handpsring facing away from the wall off the wall.", "https://www.youtube.com/watch?v=Rsv6LRwVWao"),
            ("one-handed down monkey", "A one handed gainer backhandspring off a wall..", ""),
            ("wall dive roll", "A horizontal wall run into a dive roll taking off from the wall.", "https://www.youtube.com/watch?v=rvWnAzPpyW4"),
            ("2 step wallflip", "A wall backflip after 2 steps on the wall.", "https://www.youtube.com/watch?v=1wqeofeoN8w"),
            ("2 step wall full", "A wall backflip 360 after 2 steps on the wall.", "https://www.youtube.com/watch?v=gGDn_2zAY3E"),
            ("2 step wall front", "A wall loser frontflip after 2 steps on the wall.", "https://www.youtube.com/shorts/S7FjMXxJrnQ"),
            ("tac cast", "A one step wall run followed by a castaway from either the wall or the top ledge.", "https://www.youtube.com/shorts/fiue9Ua7CyI"),
            ("3 step wallflip", "A wall backflip after 3 steps on the wall.", "https://www.youtube.com/watch?v=IIJM5AlYX44"),
            ("palm sideflip", "A sideways one handed push from the wall after a jump into a sideflip.", "https://youtu.be/hRD-pLNyrWc?t=123"),
            ("freestyle walltrick", "Any wall trick or flip.", "")
        ]
        
        let barTricks: [(name: String, about: String, linkString: String)] = [
            ("flyaway", "A forward swinging gainer from a bar.", "https://youtu.be/uFtnEMR6U6Q?t=24"),
            ("swing cast", "A backward swinging backflip from a bar with a partial casting motion intro.", "https://www.youtube.com/watch?v=1lr-rKwS8rc&ab_channel=TheCollectiveMovements"),
            ("swing dive roll", "A forward swinging dive roll off a bar.", ""),
            ("swing lache front", "A forward swinging frontflip off a bar.", "https://www.youtube.com/shorts/nh8-jcI2f44"),
            ("loser flyaway", "A backward swinging frontflip off a bar.", "https://www.youtube.com/watch?v=rPuhcoyvVV4"),
            ("baby giant", "A forward swing all the way up and around the bar in a tucked position.", "https://www.youtube.com/watch?v=Vo1bfmSABX4"),
            ("giant", "A forward swing all the way up and around the bar in a straight position.","https://www.youtube.com/watch?v=Aph0Vn06aXU"),
            ("loser flyaway 180", "A backward swinging frontflip 180 off a bar.",  ""),
            ("loser flyaway 540", "A backward swinging frontflip 540 off a bar.", ""),
            ("flyaway full", "A forward swinging backflip 360 off a bar.", "https://www.youtube.com/watch?v=rLaCPL4KJKQ"),
            ("flyaway double full", "A forward swinging backflip 720 off a bar.", "https://youtu.be/4xKmys-ydH8?t=43"),
            ("swing lache sideflip", "A forward swinging sideflip off a bar.", "https://www.youtube.com/shorts/2nLsqOhv6SA"),
            ("swing", "A forward or backward swing on a bar.", ""),
            ("cast frontflip over", "A stationary position with arms above the bar and hips against it into a cast frontflip forward over the bar.", ""),
    ("cast inward frontflip", "A cast into a loser frontflip from a bar.", "https://www.youtube.com/watch?v=gCFloU0_bg0"),
            ("bar kip", "A gymnastics fundamental where you go from hanging to a ready position with your hips against the bar and your arms pressed downward.", "https://www.youtube.com/shorts/emSJ0UnXWEE"),
            ("knee swing", "Swinging from knees under the bar in a forward motion.", "https://youtu.be/6gV6Sf6a86M?t=221"),
            ("cast gainer", "A bar cast into a gainer over the bar.", "https://www.youtube.com/watch?v=uTf8Z8iZnLQ"),
            ("freestyle bar trick", "Any bar trick or flip.",  "")
        ]
        
        let parkour: [(name: String, about: String, linkString: String)] = [
            ("wall run", "A horizontal run along a wall.","https://youtu.be/bgyrrjmavy4?t=196"),
            ("wall climb", "A one step wall run to climb on top.", "https://www.youtube.com/shorts/JD-_kp_qif4"),
            ("cat leap", "A leap to a cat position hanging from a ledge facing it with both feet and hands on wall.", "https://www.youtube.com/watch?v=1HrPnAvzP70"),
            ("gap jump", "A jump from one obstacle to another.", "https://www.youtube.com/watch?v=I5p4v5FTU5U"),
            ("plyo (2-footed precision)", "A two-footed jump onto a another object landing controlled in place.", "https://www.youtube.com/watch?v=QPMAbGkpOCk"),
            ("stride (1-footed precision)", "A one-footed jump from one object landing on the opposite foot on the second object.", "https://www.youtube.com/watch?v=4A49x5pzlSw"),
            ("crane", "A jump onto another object wherein one foot lands on the ledge while the other lands hanging against the wall.", "https://www.youtube.com/watch?v=VLi-wsr3Za4"),
            ("vertical jump up obstacle", "A two footed jump completely onto an obstacle.", " https://youtu.be/n6KkDrJE82s?t=119"),
            ("cat to cat", "A cat leap to 180 wall jump into another cat position landing.", "https://www.youtube.com/watch?v=qOduMtzjgXE"),
            ("freestyle parkour move", "Any parkour move.", "")
        ]
        
        let breakdancing: [(name: String, about: String, linkString: String)] = [
            ("thread", "Pulling one leg through the hole in between a grab such as between a hand and foot that are locked together. Like threading a needle.", ""),
            ("swipe", "A power move where the b-boy or b-girl leans back, whips his or her arms to one side to touch the ground, and his or her legs follow closely behind, twisting 360 degrees to land on the ground once again with a foot each time.", "https://www.youtube.com/shorts/e7uqPSCVtIA"),
            ("flare", "A powermove where the athlete alternates balancing the torso between either arm while swinging the legs beneath in continuous circles.", "https://www.youtube.com/shorts/M_SDO6yT9EM"),
            ("air flare", "A powermove from handstand where the athlete rotates the torso around the vertical axis of their body (extending from the head down vertically) while traveling in a circular path along a plane parallel with the floor.", "https://www.youtube.com/shorts/BPpBi9Z9nrs"),
            ("headspin", "Continuous spins while upside down on your head.", "https://www.youtube.com/shorts/td3QZLccIh8"),
            ("baby freeze", "A two-handed freeze with one leg out and one bent.", "https://www.youtube.com/shorts/aGjZIFH63XI"),
            ("chair freeze", "A one-handed freeze with one leg up resting on the other and the free hand near the hip.", "https://www.youtube.com/shorts/-itjDJdur2I"),
            ("shoulder freeze", "A freeze on the shoulder.", "https://www.youtube.com/shorts/WW9ex8QPhBo"),
            ("turtle freeze", "A two-handed freeze with both elbows pressed in and the b-boy / b-girl facing straight down in a horizontal position.", "https://www.youtube.com/watch?v=hBdeCxhHv1c&ab_channel=Vitality"),
            ("pilot freeze", "A freeze with two hands head, one foot, and one leg lifted as if about to go into a windmill.", "https://www.youtube.com/watch?v=0MBKvjfZ8pY&ab_channel=VincaniTV"),
            ("air chair", "A freeze supported by one arm, with the elbow of the supporting arm stabbed into the lower back and hips facing upward.", "https://www.youtube.com/watch?v=6nU5Jtv8_SI&ab_channel=CoachSambo"),
            ("air baby",  "A one-handed downward facing freeze with one knee being supported directly by the elbow of the hand placed on the ground.", "https://www.youtube.com/watch?v=a3QbhAZb9-4&ab_channel=EddieMoon"),
            ("air freeze", "One-handed handstand freeze", "https://www.youtube.com/shorts/gMor-VVpYO8"),
            ("backspin", "Continuous spins flat on back.", "https://www.youtube.com/shorts/1fBybIt99-c"),
            ("windmill", "A well-known powermove where the athlete spins in 360 rotations while rotating in a circle going from shoulders to upper back continuously.", "https://www.youtube.com/shorts/kL8nx3fhgFI"),
            ("halo", "A head spin starting and ending in a baby-like position.", "https://www.youtube.com/watch?v=Q5UzVegg_yM&ab_channel=TheRuggeds"),
            ("cricket", "Continous horizontal flatspins off both hands with elbows supporting.", "https://www.youtube.com/watch?v=r-XTguUIi48&ab_channel=AJ-47SoulMavericks"),
            ("jackhammers", "Continous horizontal flatspins off one hands with elbow supporting.", "https://www.youtube.com/watch?v=4FwOffyb5Q8&ab_channel=VincaniTV"),
            ("UFOs", "Two handed continous horizontal flatspins off both hands with no elbows supporting.", "https://www.youtube.com/watch?v=1qwPHvt05P4&ab_channel=BboyKastrito"),
            ("1990", "One handed vertical spins", "https://www.youtube.com/shorts/NlXJ7kTEoL0"),
            ("2000",  "Two-handed vertical spins with one hand placed on top of the other", "https://www.youtube.com/shorts/DfuF54QIlHo"),
            ("babymill", "Windmills done in a tucked criss cross like position.", "https://www.youtube.com/watch?v=-3ct09EkjCA&ab_channel=HIRONAGA"),
            ("doublemills", "Windmills with an extra spin (720 total) in each single rotation.", "https://www.youtube.com/watch?v=Mqrp3owRx_Q&ab_channel=HIRONAGA"),
            ("tombstones", "Piked / Double leg windmills", "https://www.youtube.com/shorts/xrZCmmLHuAI"),
            ("virgin flare", "A flare with legs together rather than wideflip spread", "https://www.youtube.com/watch?v=gK7H0rtzyzQ&ab_channel=VincaniTV"),
            ("coin drop", "A machine intro into a shoulder drop and back up to feet while rotating on ground.", "https://www.youtube.com/shorts/DH1F66L8CUU"),
            ("freestyle breakdance move", "Any breakdancing move.", "")
        ]
        
        let modifiers: [(name: String, about: String, linkString: String)] = [
            ("swingthrough", "A kick with one leg while jumping with the other.", "https://www.youtube.com/watch?v=AyMkzzRDM2E"),
            ("punch", "From a two-footed takeoff.", "https://youtu.be/FGVQg3Kg_J8?t=16"),
            ("half down", "with a 180 spin in the second half on the way down.", "https://www.youtube.com/shorts/7jjNqoHTtmE"),
            ("full down",  "with a 360 spin in the second half on the way down.", "https://youtu.be/X0FrGy66Gww?t=125"),
            ("with webster kick intro", "with a webster backwards kick into.",  "https://www.youtube.com/watch?v=6kIS3rEKp0Y"),
            ("nike", "In a nike pose with one leg tucked and the other out straight almost in a pike.", "https://www.youtube.com/shorts/I2gz9VIL4hk"),
            ("rodeo out", "Grab ankles and flash out into a scorpion-like pose before landing.", "https://www.youtube.com/watch?v=jGjkuWxlllE"),
            ("x-out", "Shoot both legs out in the top half of an X shape.", "https://www.youtube.com/shorts/Ea2ZEplMBDQ"),
            ("tucked", "A tuck in a ball grabbing knees or ankles", "https://www.youtube.com/shorts/r2vgWEgAJlU"),
            ("undertuck", "A tuck with hands grabbing under knees in a ball.", "https://www.youtube.com/shorts/4MSzfKvZaks"),
            ("pike", "A tuck under but with legs straight", "https://www.youtube.com/watch?v=ZY2qjQEeeCU"),
            ("kick out", "A kick before landing.", "https://youtu.be/0FAFNImN9io?t=61"),
            ("kick intro", "A kick in first half of trick before landing.", "https://www.youtube.com/watch?v=O8Vw_vpRlM0"),
            ("lazy stall", "Hands on head stall like you’re chillin.", "https://www.youtube.com/shorts/U6b0TcgN3dU"),
            ("eyes closed", "With your eyes closed.", "https://www.youtube.com/shorts/sgLwZD29Z_8"),
            ("no hands", "With no hands.", ""),
            ("one hand touch down", "Touch one hand down before landing (also known as a broken).", "https://www.youtube.com/shorts/Y9paVLo3yL4"),
            ("off knees", "Take off from one or both knees.", "https://www.youtube.com/shorts/hygfMOnq4yo"),
            ("dark side (opposite from comfortable)", "Do the previous trick the opposite direction that you are comfortable. For instance, spin right instead of left during a backflip 360.", "https://www.youtube.com/watch?v=rOZPWpH3VWM"),
            ("one footed", "Take off one foot.", "https://youtu.be/t5TE94MD2Oo?t=334"),
            ("two footed", "Take off two feet.", "https://www.youtube.com/shorts/cTBMz2k5m-I"),
            ("off hands", "Take off of hands.", "https://youtu.be/SPPo6GChrGo?t=87"),
            ("russian throw", "throw your arms behind you on takeoff.", "https://www.youtube.com/watch?v=eWgPogqvnk4"),
            ("backwards", "Do the prior trick the opposite way it was normally intended.", "https://www.youtube.com/shorts/KOaT850cArE"),
            ("inverted", "Turns a backflip into a gainer, a frontflip into a loser, etc.", "https://www.youtube.com/watch?v=rwCPpNzLX04"),
            ("low jump", "Jump low to the ground during it.", "https://www.youtube.com/shorts/_g7AxsJQ5Vk"),
            ("off drop", "Do the previous trick from a height.", "https://www.youtube.com/watch?v=wprTH1Wlslo"),
            ("onto object", "Do the previous trick onto an object elevated from the ground.", "https://youtu.be/LG7mMNphoQ8?t=421"),
            ("traveling a strange direction", "Travel in a weird direction, such as a sideways traveling backflip or kong.", "https://www.youtube.com/shorts/tQS_KYUxgDw"),
            ("precision", "Land in a precise location or on a beam.",  "https://youtu.be/P3a8WwP5Ggo?t=49"),
            ("in place", "Land in the same spot.", "https://www.youtube.com/shorts/rjVItR2vIVs"),
            ("distance", "Do the previous trick a far distance.", "https://youtu.be/LG7mMNphoQ8?t=720"),
            ("flailing", "Flail your limbs during the trick.", "https://youtu.be/t5TE94MD2Oo?t=607"),
            ("dive", "Dive in the first half of the trick.", "https://www.youtube.com/shorts/AR5qQtBZQo0"),
            ("stall", "Stall with your arms out sideways during the first half of the trick.", "https://www.youtube.com/shorts/PrQCx5metZU"),
            ("rocket boy", "Grab a pike with one hand on feet and the other hand out during trick.", "https://www.youtube.com/watch?v=acL7D1-6j7o"),
            ("to lay down (fake fail)", "Pretend to fail and lay down at the end of this trick.", "https://youtu.be/t5TE94MD2Oo?t=640"),
            ("to bar grab", "Land grabbing a bar with your hands.", "https://youtu.be/4Es8zpBzloQ?t=121")
        ]

}

